name: CICD security scan for online voting app
on: push

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Run SonarQube on SonarCloud
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=LeoPhat
            -Dsonar.projectKey=leophat
            -Dsonar.sources=.

  security:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk Compostion Analytics Scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}