name: CICD security scan for online voting app
on: push

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Run SonarQube on SonarCloud
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        # continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=leophat
            -Dsonar.projectKey=LeoPhat_Online-Voting
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes
  security:
    runs-on: ubuntu-latest
    # needs: sonarqube
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk Compostion Analytics Scan
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}